add group creation inside container

diff --git a/assets/createUser.sh.in b/assets/createUser.sh.in
--- a/assets/createUser.sh.in
+++ b/assets/createUser.sh.in
@@ -1,10 +1,11 @@
 #!/usr/bin/env bash
 set -e
 
-echo "- running apt update..."
-DEBIAN_FRONTEND=noninteractive apt-get -qq update > /dev/null
-echo "- installing sudo, tzdata, vim..."
-DEBIAN_FRONTEND=noninteractive apt-get -qq install sudo tzdata vim > /dev/null
+{{.createGroups}}
+
+echo "group_exists: ${group_exists}"
+echo "      errors: ${errors}"
+echo "-------------------------------"
 
 echo "- creating user..."
 existing_user_by_uid=`getent passwd "1000" | cut -f1 -d: || true`
@@ -15,13 +16,10 @@ existing_user_uid=`getent passwd "{{.username}}" | cut -f3 -d: || true`
 if [ -n "${existing_user_by_name}" ]; then find / -uid ${existing_user_uid} -exec chown -h {{.uid}} {} + || true ; find / -gid ${existing_user_uid} -exec chgrp -h {{.ugid}} {} + || true ; fi
 if [ -n "${existing_user_by_name}" ]; then userdel -r "${existing_user_by_name}"; fi
 
-existing_group_by_gid=`getent group "1000" | cut -f1 -d: || true`
-if [ -z "${existing_group_by_gid}" ]; then groupadd -g "{{.ugid}}" "{{.username}}"; fi
+# existing_group_by_gid=`getent group "1000" | cut -f1 -d: || true`
+# if [ -z "${existing_group_by_gid}" ]; then groupadd -g "{{.ugid}}" "{{.username}}"; fi
 
 useradd --no-log-init --no-create-home --uid "{{.uid}}" -s "/bin/bash" -c "{{.Name}}" -g "{{.ugid}}" -G "{{.gids}}" -d "{{.homedir}}" "{{.username}}"
-
-echo "{{.username}} ALL=NOPASSWD: ALL" >> /etc/sudoers.d/dogi
-sed -i '/secure_path/ s/^/#/' /etc/sudoers
 
 echo "- create homedir: {{.homedir}}"
 echo "PS1=\"🐳 \${PS1}\"" >> "/etc/skel/.bashrc"
@@ -42,6 +40,13 @@ create_bash_script() {
 
 create_bash_script matrix \
                    'dogi'
+
+echo "- running apt update..."
+DEBIAN_FRONTEND=noninteractive apt-get -qq update > /dev/null
+echo "- installing sudo, tzdata, vim..."
+DEBIAN_FRONTEND=noninteractive apt-get -qq install sudo tzdata vim > /dev/null
+echo "{{.username}} ALL=NOPASSWD: ALL" >> /etc/sudoers.d/dogi
+sed -i '/secure_path/ s/^/#/' /etc/sudoers
 
 echo "- done!"
 if [ $# -eq 0 ]
